import { expect, test } from "@playwright/test";
import { parsePackJson } from "../src/terrain/assetClient";

// Mojang's own blocks.json opens with a line comment, so this is the shape the
// vanilla baseline actually arrives in — not a hypothetical malformed file.
test("pack json tolerates the comments Mojang ships", () => {
  const text = `// Do not edit this file.\n{\n  "format_version": "1.21.0",\n  /* per-block appearance */\n  "stone": { "textures": "stone" }\n}\n`;
  const parsed = parsePackJson<Record<string, unknown>>(text);
  expect(parsed["format_version"]).toBe("1.21.0");
  expect(parsed["stone"]).toEqual({ textures: "stone" });
});

test("pack json tolerates trailing commas", () => {
  const parsed = parsePackJson<{ a: number[]; b: number }>(
    '{ "a": [1, 2, 3,], "b": 4, }',
  );
  expect(parsed.a).toEqual([1, 2, 3]);
  expect(parsed.b).toBe(4);
});

test("a // inside a string is not a comment", () => {
  const parsed = parsePackJson<{ path: string }>(
    '{ "path": "textures/blocks//stone" }',
  );
  expect(parsed.path).toBe("textures/blocks//stone");
});

test("genuinely broken json names the file", () => {
  expect(() => parsePackJson("{ nope", "blocks.json")).toThrow(/blocks\.json/);
});
