// AUTO-GENERATED by scripts/generateTypes.ts. Do not edit manually.
// Generated at 2025-09-08T14:05:54.885Z

// Shared external types mapped from Go:
import { Face, Pos, Rotation, Vec3 } from "../types";

/** Option stores index to custom form element & its value. */
export interface Option {
  index: number;
  value: any;
}

/** Slot is a slot of the inventory. */
export interface Slot {
  index: number;
  inventory: string;
}

/** Attack attacks entity from Actor's view direction. */
export interface Attack {}

/** AttackEntity is an instruction to attack an entity. */
export interface AttackEntity {
  entityRuntimeID: number;
}

/** BreakBlock is an instruction to break a block at a given position. */
export interface BreakBlock {
  pos: Pos;
}

/** Chat is an instruction to send a chat message. */
export interface Chat {
  message: string;
}

/** CustomFormRespond is an instruction to respond to a custom form. */
export interface CustomFormRespond {
  options: Option[];
  ignore: boolean;
}

/** Disconnect closes the Bot connection. */
export interface Disconnect {}

/** DropSelectedItem drops the currently held item stack. */
export interface DropSelectedItem {}

/** EditSign edits the last Sign sent to the Actor. */
export interface EditSign {
  text: string;
}

/** Interact uses the item currently held by the Actor. */
export interface Interact {}

/** InteractWithBlock uses the held item on a block at the given position. */
export interface InteractWithBlock {
  pos: Pos;
  face: Face;
  clickPos: Vec3;
}

/** Jump makes the Actor jump. */
export interface Jump {}

/** LookAtBlock turns the Actor to look at a block position. */
export interface LookAtBlock {
  pos: Pos;
}

/** LookAtEntity turns the Actor to look at an entity by runtime ID. */
export interface LookAtEntity {
  runtimeID: number;
}

/** LookAtLocation turns the Actor to look at a world-space location. */
export interface LookAtLocation {
  location: Vec3;
}

/** MenuFormRespond responds to a menu form with a selected button, or ignores it. */
export interface MenuFormRespond {
  response: number;
  ignore: boolean;
}

/** ModalFormRespond responds to a modal form with yes/no, or ignores it. */
export interface ModalFormRespond {
  response: boolean;
  ignore: boolean;
}

/** MoveRawInput moves the Actor using raw input values and delta rotation. */
export interface MoveRawInput {
  forward: boolean;
  back: boolean;
  left: boolean;
  right: boolean;
  jump: boolean;
  sneak: boolean;
  deltaRotation: Rotation;
}

/** NavigateToBlock navigates the Actor to a target block position. */
export interface NavigateToBlock {
  pos: Pos;
}

/** Rejoin triggers the handler's Rejoin() after a configurable delay. */
export interface Rejoin {
  /** Delay is a delay in seconds before re-run. */
  delay: number;
}

/** Respawn respawns the Actor at its spawn point. */
export interface Respawn {}

/** Rotate rotates the Actor to the given rotation. */
export interface Rotate {
  rotation: Rotation;
}

/** RunCommand runs a server command as the Actor. */
export interface RunCommand {
  command: string;
}

/** StopBreakingBlock aborts the current block breaking action. */
export interface StopBreakingBlock {}

/** StopNavigating stops the current navigation. */
export interface StopNavigating {}

/** StopUsingItem releases the currently used item. */
export interface StopUsingItem {}

/** ToggleCrafterSlot toggles crafter slot. */
export interface ToggleCrafterSlot {
  slot: number;
  pos: Pos;
  disabled: boolean;
}

export type InstructionAction =
  | "attack"
  | "attackEntity"
  | "breakBlock"
  | "chat"
  | "customFormRespond"
  | "disconnect"
  | "dropSelectedItem"
  | "editSign"
  | "interact"
  | "interactWithBlock"
  | "jump"
  | "lookAtBlock"
  | "lookAtEntity"
  | "lookAtLocation"
  | "menuFormRespond"
  | "modalFormRespond"
  | "moveRawInput"
  | "navigateToBlock"
  | "rejoin"
  | "respawn"
  | "rotate"
  | "runCommand"
  | "stopBreakingBlock"
  | "stopNavigating"
  | "stopUsingItem"
  | "toggleCrafterSlot";

export interface InstructionParametersByAction {
  attack: Attack;
  attackEntity: AttackEntity;
  breakBlock: BreakBlock;
  chat: Chat;
  customFormRespond: CustomFormRespond;
  disconnect: Disconnect;
  dropSelectedItem: DropSelectedItem;
  editSign: EditSign;
  interact: Interact;
  interactWithBlock: InteractWithBlock;
  jump: Jump;
  lookAtBlock: LookAtBlock;
  lookAtEntity: LookAtEntity;
  lookAtLocation: LookAtLocation;
  menuFormRespond: MenuFormRespond;
  modalFormRespond: ModalFormRespond;
  moveRawInput: MoveRawInput;
  navigateToBlock: NavigateToBlock;
  rejoin: Rejoin;
  respawn: Respawn;
  rotate: Rotate;
  runCommand: RunCommand;
  stopBreakingBlock: StopBreakingBlock;
  stopNavigating: StopNavigating;
  stopUsingItem: StopUsingItem;
  toggleCrafterSlot: ToggleCrafterSlot;
}

export type InstructionPayload =
  | { action: "attack"; parameters: Attack }
  | { action: "attackEntity"; parameters: AttackEntity }
  | { action: "breakBlock"; parameters: BreakBlock }
  | { action: "chat"; parameters: Chat }
  | { action: "customFormRespond"; parameters: CustomFormRespond }
  | { action: "disconnect"; parameters: Disconnect }
  | { action: "dropSelectedItem"; parameters: DropSelectedItem }
  | { action: "editSign"; parameters: EditSign }
  | { action: "interact"; parameters: Interact }
  | { action: "interactWithBlock"; parameters: InteractWithBlock }
  | { action: "jump"; parameters: Jump }
  | { action: "lookAtBlock"; parameters: LookAtBlock }
  | { action: "lookAtEntity"; parameters: LookAtEntity }
  | { action: "lookAtLocation"; parameters: LookAtLocation }
  | { action: "menuFormRespond"; parameters: MenuFormRespond }
  | { action: "modalFormRespond"; parameters: ModalFormRespond }
  | { action: "moveRawInput"; parameters: MoveRawInput }
  | { action: "navigateToBlock"; parameters: NavigateToBlock }
  | { action: "rejoin"; parameters: Rejoin }
  | { action: "respawn"; parameters: Respawn }
  | { action: "rotate"; parameters: Rotate }
  | { action: "runCommand"; parameters: RunCommand }
  | { action: "stopBreakingBlock"; parameters: StopBreakingBlock }
  | { action: "stopNavigating"; parameters: StopNavigating }
  | { action: "stopUsingItem"; parameters: StopUsingItem }
  | { action: "toggleCrafterSlot"; parameters: ToggleCrafterSlot };
