// AUTO-GENERATED by scripts/generateTypes.ts. Do not edit manually.
// Generated at 2026-07-26T21:25:24.067Z

// Shared external types mapped from Go:
import { Face, Pos, Rotation, Vec3 } from "../types";

/** Option stores index to custom form element & its value. */
export interface Option {
  index: number;
  value: any;
}

/** Slot is a slot of the inventory. */
export interface Slot {
  index: number;
  inventory: string;
}

/** Attack attacks entity from Actor's view direction. */
export interface Attack {}

/** AttackEntity is an instruction to attack an entity. */
export interface AttackEntity {
  entityRuntimeID: number;
}

/** BreakBlock is an instruction to break a block at a given position. */
export interface BreakBlock {
  pos: Pos;
}

/** Chat is an instruction to send a chat message. */
export interface Chat {
  message: string;
}

/** ClickFormButton presses a menu or modal form button by text or index. */
export interface ClickFormButton {
  text: string;
  index: number;
}

/** CustomFormRespond is an instruction to respond to a custom form. */
export interface CustomFormRespond {
  options: Option[];
  ignore: boolean;
}

/** DialogueResponse responds to dialogue. */
export interface DialogueResponse {
  buttonIndex: number;
  ignore: boolean;
}

/** Disconnect closes the Bot connection. */
export interface Disconnect {}

/** DropSelectedItem drops the currently held item stack. */
export interface DropSelectedItem {}

/** EditSign edits the last Sign sent to the Actor. */
export interface EditSign {
  text: string;
}

/** GetBlock returns a block at a position from the bot's tracked world. */
export interface GetBlock {
  pos: Pos;
}

/** GetForm returns the currently open form without consuming it. */
export interface GetForm {}

/** GetInventory returns the bot's inventory contents. */
export interface GetInventory {}

/** GetMessages returns recent received chat/system messages. */
export interface GetMessages {
  limit: number;
}

/** GetNearbyEntities returns entities within a radius of the bot. */
export interface GetNearbyEntities {
  radius: number;
}

/** GetState returns the bot's current actor state. */
export interface GetState {}

/** Interact uses the item currently held by the Actor. */
export interface Interact {}

/** InteractWithBlock uses the held item on a block at the given position. */
export interface InteractWithBlock {
  pos: Pos;
  face: Face;
  clickPos: Vec3;
}

/** InventoryAction performs inventory action. */
export interface InventoryAction {
  source: Slot;
  destination: Slot;
  action: string;
  count: number;
}

/** Jump makes the Actor jump. */
export interface Jump {}

/** LookAtBlock turns the Actor to look at a block position. */
export interface LookAtBlock {
  pos: Pos;
}

/** LookAtEntity turns the Actor to look at an entity by runtime ID. */
export interface LookAtEntity {
  runtimeID: number;
}

/** LookAtLocation turns the Actor to look at a world-space location. */
export interface LookAtLocation {
  location: Vec3;
}

/** MenuFormRespond responds to a menu form with a selected button, or ignores it. */
export interface MenuFormRespond {
  response: number;
  ignore: boolean;
}

/** ModalFormRespond responds to a modal form with yes/no, or ignores it. */
export interface ModalFormRespond {
  response: boolean;
  ignore: boolean;
}

/** MoveRawInput moves the Actor using raw input values and delta rotation. */
export interface MoveRawInput {
  forward: boolean;
  back: boolean;
  left: boolean;
  right: boolean;
  jump: boolean;
  sneak: boolean;
  deltaRotation: Rotation;
}

/** NavigateToBlock navigates the Actor to a target block position. */
export interface NavigateToBlock {
  pos: Pos;
}

/** PlaceBlock places the held block at the given position. */
export interface PlaceBlock {
  pos: Pos;
}

/** Rejoin triggers the handler's Rejoin() after a configurable delay. */
export interface Rejoin {
  /** Delay is a delay in seconds before re-run. */
  delay: number;
}

/** Respawn respawns the Actor at its spawn point. */
export interface Respawn {}

/** Rotate rotates the Actor to the given rotation. */
export interface Rotate {
  rotation: Rotation;
}

/** RunCommand runs a server command as the Actor. */
export interface RunCommand {
  command: string;
}

/** SetHeldSlot sets the currently held hotbar slot. */
export interface SetHeldSlot {
  slot: number;
}

/** StopBreakingBlock aborts the current block breaking action. */
export interface StopBreakingBlock {}

/** StopNavigating stops the current navigation. */
export interface StopNavigating {}

/** StopUsingItem releases the currently used item. */
export interface StopUsingItem {}

/** ToggleCrafterSlot toggles crafter slot. */
export interface ToggleCrafterSlot {
  slot: number;
  pos: Pos;
  disabled: boolean;
}

/** WaitForForm blocks until a form is open, then returns the same shape as getForm. */
export interface WaitForForm {
  timeoutMs: number;
}

/** WaitForMessage blocks until a received message matches contains and/or regex. */
export interface WaitForMessage {
  contains: string;
  regex: string;
  timeoutMs: number;
}

export type InstructionAction =
  | "attack"
  | "attackEntity"
  | "breakBlock"
  | "chat"
  | "clickFormButton"
  | "customFormRespond"
  | "dialogueResponse"
  | "disconnect"
  | "dropSelectedItem"
  | "editSign"
  | "getBlock"
  | "getForm"
  | "getInventory"
  | "getMessages"
  | "getNearbyEntities"
  | "getState"
  | "interact"
  | "interactWithBlock"
  | "inventoryAction"
  | "jump"
  | "lookAtBlock"
  | "lookAtEntity"
  | "lookAtLocation"
  | "menuFormRespond"
  | "modalFormRespond"
  | "moveRawInput"
  | "navigateToBlock"
  | "placeBlock"
  | "rejoin"
  | "respawn"
  | "rotate"
  | "runCommand"
  | "setHeldSlot"
  | "stopBreakingBlock"
  | "stopNavigating"
  | "stopUsingItem"
  | "toggleCrafterSlot"
  | "waitForForm"
  | "waitForMessage";

export interface InstructionParametersByAction {
  attack: Attack;
  attackEntity: AttackEntity;
  breakBlock: BreakBlock;
  chat: Chat;
  clickFormButton: ClickFormButton;
  customFormRespond: CustomFormRespond;
  dialogueResponse: DialogueResponse;
  disconnect: Disconnect;
  dropSelectedItem: DropSelectedItem;
  editSign: EditSign;
  getBlock: GetBlock;
  getForm: GetForm;
  getInventory: GetInventory;
  getMessages: GetMessages;
  getNearbyEntities: GetNearbyEntities;
  getState: GetState;
  interact: Interact;
  interactWithBlock: InteractWithBlock;
  inventoryAction: InventoryAction;
  jump: Jump;
  lookAtBlock: LookAtBlock;
  lookAtEntity: LookAtEntity;
  lookAtLocation: LookAtLocation;
  menuFormRespond: MenuFormRespond;
  modalFormRespond: ModalFormRespond;
  moveRawInput: MoveRawInput;
  navigateToBlock: NavigateToBlock;
  placeBlock: PlaceBlock;
  rejoin: Rejoin;
  respawn: Respawn;
  rotate: Rotate;
  runCommand: RunCommand;
  setHeldSlot: SetHeldSlot;
  stopBreakingBlock: StopBreakingBlock;
  stopNavigating: StopNavigating;
  stopUsingItem: StopUsingItem;
  toggleCrafterSlot: ToggleCrafterSlot;
  waitForForm: WaitForForm;
  waitForMessage: WaitForMessage;
}

export type InstructionPayload =
  | { action: "attack"; parameters: Attack }
  | { action: "attackEntity"; parameters: AttackEntity }
  | { action: "breakBlock"; parameters: BreakBlock }
  | { action: "chat"; parameters: Chat }
  | { action: "clickFormButton"; parameters: ClickFormButton }
  | { action: "customFormRespond"; parameters: CustomFormRespond }
  | { action: "dialogueResponse"; parameters: DialogueResponse }
  | { action: "disconnect"; parameters: Disconnect }
  | { action: "dropSelectedItem"; parameters: DropSelectedItem }
  | { action: "editSign"; parameters: EditSign }
  | { action: "getBlock"; parameters: GetBlock }
  | { action: "getForm"; parameters: GetForm }
  | { action: "getInventory"; parameters: GetInventory }
  | { action: "getMessages"; parameters: GetMessages }
  | { action: "getNearbyEntities"; parameters: GetNearbyEntities }
  | { action: "getState"; parameters: GetState }
  | { action: "interact"; parameters: Interact }
  | { action: "interactWithBlock"; parameters: InteractWithBlock }
  | { action: "inventoryAction"; parameters: InventoryAction }
  | { action: "jump"; parameters: Jump }
  | { action: "lookAtBlock"; parameters: LookAtBlock }
  | { action: "lookAtEntity"; parameters: LookAtEntity }
  | { action: "lookAtLocation"; parameters: LookAtLocation }
  | { action: "menuFormRespond"; parameters: MenuFormRespond }
  | { action: "modalFormRespond"; parameters: ModalFormRespond }
  | { action: "moveRawInput"; parameters: MoveRawInput }
  | { action: "navigateToBlock"; parameters: NavigateToBlock }
  | { action: "placeBlock"; parameters: PlaceBlock }
  | { action: "rejoin"; parameters: Rejoin }
  | { action: "respawn"; parameters: Respawn }
  | { action: "rotate"; parameters: Rotate }
  | { action: "runCommand"; parameters: RunCommand }
  | { action: "setHeldSlot"; parameters: SetHeldSlot }
  | { action: "stopBreakingBlock"; parameters: StopBreakingBlock }
  | { action: "stopNavigating"; parameters: StopNavigating }
  | { action: "stopUsingItem"; parameters: StopUsingItem }
  | { action: "toggleCrafterSlot"; parameters: ToggleCrafterSlot }
  | { action: "waitForForm"; parameters: WaitForForm }
  | { action: "waitForMessage"; parameters: WaitForMessage };
