name: Go Lint

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  golangci:
    name: Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Vet
        run: go vet ./...

      - name: Formatting
        run: test -z $(go fmt ./...)